title: Marcos Esparza 
logo: /assets/img/LinkedIn Profile Pic.PNG
#description: Mechanical Engineering student with hands-on experience in aerospace systems and high-power rocketry, seeking a role where I can contribute to testing and analysis while deepening my technical skills through real engineering work.
show_downloads: true
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme

sass:
  style: compressed
