title: Marcos Esparza 
logo: /assets/img/LinkedIn Profile Pic.PNG
description: Mechanical Engineering student with experience in design, analysis, and mechanical/aerospace systems.
show_downloads: true
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
sass:
  style: compressed
